version: "3"

services:

  web:
    build: ./
    ports:
      - "443:443"
    volumes:
      - ./:/code
    command: python manage.py runsslserver --certificate melietju_fr.crt --key private.key  0.0.0.0:443