# Generated by Django 3.1 on 2020-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200810_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='scoreUser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historique',
            name='scoreUser2',
            field=models.IntegerField(default=0),
        ),
    ]
