# Generated by Django 3.1 on 2020-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200810_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
