# Generated by Django 3.1 on 2020-08-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_categorie_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='categorie',
            field=models.ManyToManyField(to='application.Categorie'),
        ),
    ]
