# Generated by Django 3.1 on 2020-08-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_historique_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='application.Categorie'),
        ),
    ]
