# Generated by Django 3.1 on 2020-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200811_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='musique',
            name='use',
            field=models.BooleanField(default=False),
        ),
    ]
