# Generated by Django 3.1 on 2020-08-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_musique_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='use',
            field=models.BooleanField(default=True),
        ),
    ]
