# Generated by Django 3.1 on 2020-09-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_challenge_challengegroups_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengegroups',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
