# Generated by Django 3.1 on 2020-09-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20200906_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photobooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
